server:
  port: 80 # 服务器端口号

spring:
  application:
    name: member-service-consumer # 服务名称
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1 # 采样率值介于 0 到 1 之间，1 则表示全部采集

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）
      #defaultZone: http://eureka9001.com:9001/eureka
      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（集群）
      defaultZone: http://eureka9001.com:9001/eureka/,http://eureka9002.com:9002/eureka/
  instance:
    instance-id: member-80 # 主机名称:服务名称修改
    prefer-ip-address: true     # 访问路径可以显示IP地址