server:
  port: 20000 # 服务器端口号

spring:
  application:
    name: e-commerce-gateway # 服务名称

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: member_routh01                  # 路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://member-service-provider   # 匹配后提供服务的路由地址
          predicates:
            - Path=/member/query/**           # 断言，路径相匹配的进行路由


        - id: member_routh01                  # 路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://member-service-provider   # 匹配后提供服务的路由地址
          predicates:
            - Path=/member/save               # 断言，路径相匹配的进行路由

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）
      #defaultZone: http://eureka9001.com:9001/eureka
      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（集群）
      defaultZone: http://eureka9001.com:9001/eureka/,http://eureka9002.com:9002/eureka/
  instance:
    instance-id: gateway-20000 # 主机名称:服务名称修改
    prefer-ip-address: true     # 访问路径可以显示IP地址